# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'YagnikPractical_Intuz' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for YagnikPractical_Intuz
    pod 'Alamofire'
    pod 'ReachabilitySwift'
    pod 'SDWebImage'
    pod 'NVActivityIndicatorView'

end
